### ISSUE TITLE
Example in README doesn't cancel device capture

### ISSUE THREAD

**Issue by joshwaiam** [Rami-Sabbagh/node-interception#13]
Hi there!  When testing the example provided in the README, pressing the Escape key did not actually restore keyboard and mouse functionality.  Adding `interception.destroy()` just before `break` in the device escape logic appears to resolve this issue!

```typescript
    if (
      !device ||
      !stroke ||
      (stroke?.type === 'keyboard' && stroke.code === SCANCODE_ESC)
    ) {
      interception.destroy()
      break
    }
```

**Comment by Rami-Sabbagh** [comment]
Fixed in #14
A release has been scheduled at `SAT 2021-09-04`
